name: Testowanie aplikacji

on: [push]

jobs:
  check_python_version:
    name: Sprawdzanie wersji Pythona
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v2

    - name: Wyświetlanie wersji Pythona
      run: python --version

  pylint:
    name: Testowanie aplikacji za pomocą Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v2

    - name: Instalowanie Pythona
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Instalowanie zależności
      run: pip install -r requirements.txt

    - name: Uruchamianie Pylint
      run: pylint your_app.py