name: Testowanie aplikacji

on: [push]

jobs:
  check_python_version:
    name: Sprawdzanie wersji Pythona
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v2

    - name: Wyświetlanie wersji Pythona
      run: python --version

  pylint:
    name: Testowanie aplikacji za pomocą Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')